### ISSUE TITLE
平日課題1：Git, Githubに関する課題

### ISSUE THREAD

**Issue by asosori** [asosori/camp_weekday_task1#2]
<h1>課題詳細</h1>
以下の手順(課題1-1~課題1-14)に従い、Railsで作成したアプリをGit、Githubで管理してください。 
 以降の平日課題は今回の手順同様にGit, Githubで管理するようにしてください。
<h1>課題リンク</h1>
<a href="https://interncamp.gitbook.io/ruby/exercises/week01/exercise01#undefined">平日課題1：Git, Githubに関する課題</a>
<h1>受け入れ基準</h1>

- [x] 指定のURLからリポジトリを正しくforkできていること。

- [x] forkしたリポジトリのissuesが有効になっていること。

- [x] forkしたリポジトリにIssueの作成ができていること。

- [x] forkしたリポジトリからローカルリポジトリにcloneできていること。

- [x] masterブランチから派生したtopic-exercise01を作成できていること。

- [x] Railsアプリの作成ができていること。

- [x] vendor/bundleをGit対象外にしていること

- [x] ステージングエリアに登録後、コミットできていること。

- [x] scaffoldを使用し、ステージングエリアに登録後、コミットできていること。

- [x] topic-exercise01のリモートブランチが作成できていること。

- [x] masterブランチに対してmergeするようにPR(プルリクエスト)を出していること。

- [x] 自分以外のキャンプ生に対してレビュー依頼を出していること。

**Comment by N-Ryo** [comment]
内容自体は問題ないのですが、Issueのセルフチェックのために、 `受け入れ基準` の部分をチェックボックスにしておくことをオススメします！

---
Issue作成時のエディタのメニューバーにリスト形式のアイコンが３つ並んでいると思います。
それぞれ、以下のような機能です。
※知ってたらすみません。
1. 黒点のリスト
2. 数字つきリスト
3. チェックボックスリスト

**Comment by asosori** [comment]
たしかにそうですね！

直しておきます。

レビュー担当の方でもないのに、わざわざありがとうございます！！

**Comment by tassssra** [comment]
マークダウンお疲れ様です！
見やすいです！
